name: ci
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & test (Gradle)
        run: ./gradlew -q test jacocoTestReport
      # Optional: upload perf log if present
      - name: Upload perf log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: perf-log
          path: z5d_performance_log.csv
          if-no-files-found: ignore
          retention-days: 7
  

  tsvf-tests:
    name: TSVF Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r python/requirements.txt
      - name: Run TSVF unit tests
        run: |
          PYTHONPATH=python python3 tests/test_tsvf.py -v
      - name: Run TSVF benchmarks
        run: |
          PYTHONPATH=python python3 python/tsvf_metrics.py
      - name: Upload TSVF metrics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tsvf-metrics
          path: |
            logs/tsvf_metrics.csv
            logs/tsvf_metrics.jsonl
            logs/tsvf_summary.md
          if-no-files-found: ignore
          retention-days: 7
  
