name: ci
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & test (Gradle)
        run: ./gradlew -q test jacocoTestReport
      # Optional: upload perf log if present
      - name: Upload perf log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: perf-log
          path: z5d_performance_log.csv
          if-no-files-found: ignore
          retention-days: 7
  
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r python/requirements.txt
      - name: Run Python tests
        run: |
          python3 tests/test_factorization_256bit.py
  
  monte-carlo-tests:
    name: Monte Carlo Tests
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r python/requirements.txt
      - name: Run Monte Carlo tests
        run: |
          PYTHONPATH=python python3 tests/test_monte_carlo.py
      - name: Run quick benchmark
        run: |
          PYTHONPATH=python python3 -c "
          import time
          import sys
          sys.path.insert(0, 'python')
          from monte_carlo import MonteCarloEstimator, FactorizationMonteCarloEnhancer
          import numpy as np
          
          print('=' * 70)
          print('Monte Carlo Quick Benchmark (CI)')
          print('=' * 70)
          print(f'OS: ${{ matrix.os }}')
          print(f'Python: ${{ matrix.python-version }}')
          print(f'NumPy: {np.__version__}')
          print('=' * 70)
          
          # Benchmark 1: π estimation
          estimator = MonteCarloEstimator(seed=42)
          start = time.time()
          pi_est, error, var = estimator.estimate_pi(N=100000)
          elapsed = time.time() - start
          print(f'π estimation (N=100k): {pi_est:.6f} ± {error:.6f} in {elapsed:.2f}s')
          
          # Benchmark 2: Factorization sampling (N=899, factors are 29×31)
          enhancer = FactorizationMonteCarloEnhancer(seed=42)
          
          # Test uniform mode
          start = time.time()
          candidates_uniform = enhancer.biased_sampling_with_phi(N=899, num_samples=500, mode='uniform')
          elapsed_uniform = time.time() - start
          cand_per_sec_uniform = len(candidates_uniform) / elapsed_uniform if elapsed_uniform > 0 else 0
          print(f'φ-biased sampling uniform (N=899): {len(candidates_uniform)} candidates in {elapsed_uniform:.3f}s ({cand_per_sec_uniform:.0f} cand/s)')
          
          # Test QMC mode
          start = time.time()
          candidates_qmc = enhancer.biased_sampling_with_phi(N=899, num_samples=500, mode='qmc')
          elapsed_qmc = time.time() - start
          cand_per_sec_qmc = len(candidates_qmc) / elapsed_qmc if elapsed_qmc > 0 else 0
          print(f'φ-biased sampling QMC (N=899): {len(candidates_qmc)} candidates in {elapsed_qmc:.3f}s ({cand_per_sec_qmc:.0f} cand/s)')
          
          # Check if we found the factors
          if 29 in candidates_uniform or 31 in candidates_uniform:
              print('✓ Factor found in φ-biased uniform candidates!')
          if 29 in candidates_qmc or 31 in candidates_qmc:
              print('✓ Factor found in φ-biased QMC candidates!')
          
          print('=' * 70)
          print('CI Performance Guardrail (perf regression detection):')
          print(f'  Uniform mode: {cand_per_sec_uniform:.0f} candidates/sec')
          print(f'  QMC mode: {cand_per_sec_qmc:.0f} candidates/sec')
          print('  (Baseline expectation: >1000 cand/s on modern hardware)')
          print('=' * 70)
          
          # CI guardrail: Fail if performance degrades significantly
          if cand_per_sec_uniform < 100:
              print('⚠ WARNING: Uniform mode performance below 100 cand/s')
          if cand_per_sec_qmc < 100:
              print('⚠ WARNING: QMC mode performance below 100 cand/s')
          "
  
  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python, java
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3